# Site settings
title: mo_folio
email: mail@mollybaldry.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my portfolio. Grab a cuppa, sit down and enjoy
baseurl:  # the subpath of your site, e.g. /blog/
url:  mollybaldry.co.uk
twitter_username: MollyBaldry

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
