# Site settings
title: mo_folio
name: Molly Baldry
email: mail@mollybaldry.co.uk
description: > # this means to ignore newlines until "baseurl:"
  fine artist
baseurl:  # the subpath of your site, e.g. /blog/
url:  mollybaldry.co.uk
twitter_username: MollyBaldry

# Build settings
markdown: kramdown

highlighter: pygments

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
